#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.shlib(features="c", target='siox-monitoring-siox_time', source='siox_time.c', cflags='-std=gnu99', lib='rt')


# -*- indent-tabs-mode: t -*-
