#! /usr/bin/env python
# encoding: utf-8


def build(bld):
    bld.shlib(includes="", use="BOOST siox-core-AutoRegistrar", target = "siox-monitoring-FileAssociationMapper", source = 'FileAssociationMapper.cpp' )
    bld.recurse(['test'], mandatory=True)
    bld.install_files('${PREFIX}/include/' + bld.path.relpath(), 'FileAssociationMapperOptions.hpp')


# -*- indent-tabs-mode: t -*-
