#! /usr/bin/env python
# encoding: utf-8


def build(bld):
    bld.shlib(includes="", use="BOOST siox-core-AutoRegistrar", target = "siox-monitoring-FileBasedSystemInformation", source = 'FileBasedSystemInformation.cpp' )
    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
