#!/usr/bin/env python
# encoding: utf-8

# Waf documentation, see http://docs.waf.googlecode.com/git/book_16/single.html

def build(bld):
        # ZTU1
	bld.shlib(includes="",  use = "AutoConfigurator core-container-serializer AutoRegistrar" ,  target = 'FileConfigurationProvider', source = 'FileConfigurationProvider.cpp' )
	bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
