#!/usr/bin/env python
# encoding: utf-8

# Waf documentation, see http://docs.waf.googlecode.com/git/book_16/single.html

def build(bld):
	bld.shlib( use = "AutoConfigurator" ,  target = 'FileConfigurationProvider', source = 'FileConfigurationProvider.cpp' )
	bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
