#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    #bld.shlib( use = "activity_multiplexer" ,  target = 'test-module', source = 'test-module.cpp', install_path = None,)
    src = '../ActivityMultiplexerListener_Impl1.cpp ../ActivityMultiplexer_Impl1.cpp Activity.cpp main_test_01_basic-functionality.cpp'
    bld.program( features='test cxx cxxprogram', target = 'activity-multiplexer-test', lib=['pthread'], source = src, install_path = None,)

# -*- indent-tabs-mode: t -*-
