#ifndef ACTIVITY_PLUGIN_DEREFERENCING_FACADE_IMPL_H_
#define ACTIVITY_PLUGIN_DEREFERENCING_FACADE_IMPL_H_


#include <knowledge/activity_plugin/ActivityPluginDereferencing.hpp>

#define MONITORING_ACTIVITY_PLUGIN_DEREFERENCING_INSTANCIATOR_NAME MODULE_INSTANCIATOR_NAME(monitoring_activity_plugin_dereferencing)

#endif


