#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(includes="",  features='test cxx cxxprogram', use = "", target = 'component-naming-test', source = 'component-naming-test.cpp', install_path = None)

# -*- indent-tabs-mode: t -*-
