#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.shlib(includes="include", use="AutoConfigurator AutoRegistrar", target='ReasonerStandardImplementation', source='ReasonerStandardImplementation.cpp' )

    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
