#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(includes="",  features='test cxx cxxprogram', use = "siox-core-ModuleLoader siox-monitoring-FileAssociationMapper", target = 'file-associationmapper-test', source = 'file-associationmapper-test.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
