#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(include="include",  features='test cxx cxxprogram', use = "module-loader FileAssociationMapper", target = 'file-associationmapper-test', source = 'file-associationmapper-test.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
