// Generic flags for file open modes
enum HDF5FileFlags {
	HDF5_ACCESS_RDWR = 1,
	HDF5_ACCESS_RDONLY = 2,
	HDF5_ACCESS_TRUNCATE = 4,
	HDF5_ACCESS_EXCLUSIVE = 8,
	HDF5_ACCESS_DEBUG = 16,
	HDF5_ACCESS_CREATE = 32,
};
