#!/usr/bin/env python
# encoding: utf-8

# Waf documentation, see http://docs.waf.googlecode.com/git/book_16/single.html

from waflib import Logs

import os


def build(bld):
	bld(rule="${CODEGEN} -o ${TGT} -i ${SRC}", source="ModuleOptions.hpp", target="BoostXMLSerializable.cpp", name="AutoConfiguratorModule")


	bld.shlib(includes="",  use = "siox-core-ModuleLoader BOOST siox-core-ContainerSerializer siox-core-ComponentRegistrar" ,  target = 'siox-core-AutoConfigurator', source = 'AutoConfigurator.cpp BoostXMLSerializable.cpp', depends_on="AutoConfiguratorModule" )

	bld.recurse(["ConfigurationProviderPlugins"]);


def __recurse(ctx):
	workDir = ctx.path.abspath()
	dirs = [ name for name in os.listdir(workDir)    if   os.path.isdir(os.path.join(workDir, name)) and not name.startswith(".") ]
	Logs.debug("walk into " + workDir)
	ctx.recurse(dirs, mandatory=False)

def options(opt):
	__recurse(opt)
	
def configure(conf):
	__recurse(conf)

def install(ctx):
	__recurse(ctx)

def clean(ctx):
	__recurse(ctx)

def distcheck(ctx):
	__recurse(ctx)

def distclean(ctx):
	__recurse(ctx)

def step(ctx):
	__recurse(ctx)

def uninstall(ctx):
	__recurse(ctx)


# -*- indent-tabs-mode: t -*-
