#! /usr/bin/env python
# encoding: utf-8

def build(bld):

    bld.shlib(includes="", use="BOOST core-container-serializer AutoConfigurator AutoRegistrar", target='ActivityPluginDereferencingStandardImpl', source='ActivityPluginDereferencingStandardImpl.cpp' )

