#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(includes="",  features='test cxx cxxprogram', use = "siox-monitoring-statisticsPlugin-CPUstats siox-core-AutoConfigurator", target = 'cpustatsTest', source = 'cpustatsTest.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
