#! /usr/bin/env python
# encoding: utf-8


def build(bld):
    bld.shlib( target = "FileOntology", source = 'FileOntology.cpp' )
   # bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
