#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld.program( features='test cxx cxxprogram', use = "AutoConfigurator" ,  target = 'fileconfiguration-test',	source = 'fileconfiguration-test.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
