#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld(features="seq", rule="${CODEGEN} -o ${TGT} -i ${SRC}", source="test-serialize-modules.hpp", target="BoostXMLSerializable.cpp")

	bld.shlib(includes="", use="siox-core-AutoConfigurator ", target = 'test-serialize-modules', source = 'test-serialize-modules.cpp', install_path = None )
	bld.program(includes="",  features='test cxx cxxprogram', use = "siox-core-AutoConfigurator  test-serialize-modules" ,  target = 'fileconfiguration-test',	source = 'fileconfiguration-test.cpp BoostXMLSerializable.cpp', install_path = None)

# -*- indent-tabs-mode: t -*-
