#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.shlib(includes=["#/monitoring"], use='siox-monitoring-siox_time', target='siox-monitoring-ActivityBuilder', source='ActivityBuilder.cpp')

    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
