#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld(features="seq", rule="${CODEGEN} -o ${TGT} -i ${SRC}", source="test-serializer.hpp", target="BoostXMLSerializable.cpp")

	bld(features="seq", rule="${CODEGEN} -s JBinary -o ${TGT} -i ${SRC}", source="test-bin-serializer.hpp", target="test-bin-serializerBinary.hpp", name = "test-bin-serializerBinary")

	bld.program(includes="",  features='seq test cxx cxxprogram', use = "BOOST siox-core-ContainerSerializer",  target = 'test-serializer', source = 'test-serializer.cpp BoostXMLSerializable.cpp', install_path = None)

	bld.program(includes="#", features='seq test cxx cxxprogram', use = "",  target = 'test-bin-serializer', source = 'test-bin-serializer.cpp',  install_path = None)

# -*- indent-tabs-mode: t -*-
