#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld.program(includes="",  features='test cxx cxxprogram', use = "BOOST core-ContainerSerializer",  target = 'test-serializer', source = 'test-serializer.cpp', install_path = None)

# -*- indent-tabs-mode: t -*-
