#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld.program(includes="",  features='test cxx cxxprogram', target = 'test-comm-interfaces',	source = 'test-comm-interfaces.cpp', install_path = None, )

# -*- indent-tabs-mode: t -*-
