#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(includes="",  features='test cxx cxxprogram', use = "siox-monitoring-statisticsPlugin-IOstats siox-core-AutoConfigurator", target = 'iostatsTest', source = 'iostatsTest.cpp', install_path = None)

# -*- indent-tabs-mode: t -*-
