#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(includes="",  features='test cxx cxxprogram', use = "siox-core-MathematicalEquation" ,	target = "MathematicalEquationTest", source = 'MathematicalEquationTest.cpp', )


# -*- indent-tabs-mode: t -*-
