#ifndef __SYSTEMINFO_IMPL_H
#define __SYSTEMINFO_IMPL_H

#include <monitoring/system_information/SystemInformationGlobalIDManager.hpp>

#define MONITORING_SYSTEMINFORMATION_GLOBAL_ID_INSTANCIATOR_NAME MODULE_INSTANCIATOR_NAME(monitoring_systeminformation_global_id)

#endif
