#! /usr/bin/env python
# encoding: utf-8

def build(bld):
   bld.program( features='test cxx cxxprogram', use = "BOOST" ,  target = 'ActivitySerializerTest', source = 'ActivitySerializerTest.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
