#! /usr/bin/env python
# encoding: utf-8


def build(bld):
	bld.shlib(includes="include",  target = 'core-component-registrar', source = 'ComponentRegistrar.cpp' )
	#bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
