#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld(rule="${CODEGEN} -o ${TGT} -i ${SRC}", source="ActivityFileWriterOptions.hpp", target="BoostXMLSerializable.cpp")	

	bld.shlib(includes="",  use = "BOOST siox-core-ContainerSerializer siox-core-AutoConfigurator ", target = 'siox-monitoring-activityPlugin-ActivityFileWriter', source = 'ActivityFileWriter.cpp BoostXMLSerializable.cpp' )

	bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
