#! /usr/bin/env python
# encoding: utf-8


def build(bld):
	bld.shlib(includes="",  use = "GMODULES", target = 'siox-core-ModuleLoader', source = 'module-loader.cpp' )
	bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
