#! /usr/bin/env python
# encoding: utf-8


def build(bld):
	bld.shlib( use = "GMODULES" ,  target = 'module-loader', source = 'module-loader.cpp' )
	bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
