#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(include="include",  features='test cxx cxxprogram', use = "AnomalySkeleton AutoConfigurator", target = 'ProviderSkeletonTest', source = 'ProviderSkeletonTest.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
