#! /usr/bin/env python
# encoding: utf-8

def build(bld):	
	bld(rule="${CODEGEN} -o ${TGT} -i ${SRC}", source="CommInMemoryOptions.hpp", target="BoostXMLSerializable.cpp", name="CommInMemoryOptions")

	bld.shlib(includes="", use="BOOST ", target = "siox-core-comm-inmemory", source = 'CommInMemory.cpp BoostXMLSerializable.cpp', depends_on="CommInMemoryOptions")
	
	bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
