#ifndef KNOWLEDGE_OPTIMIZER_PLUGIN_IMPL_HPP
#define KNOWLEDGE_OPTIMIZER_PLUGIN_IMPL_HPP

#include <knowledge/optimizer/OptimizerPlugin.hpp>

#define KNOWLEDGE_OPTIMIZER_PLUGING_INSTANCIATOR_NAME MODULE_INSTANCIATOR_NAME(knowledge_optimizer_plugin)

#endif
