#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.shlib(includes="",  use = "siox-core-AutoConfigurator BOOST", target = 'siox-monitoring-statisticsPlugin-CPUstats', source = 'cpustats.cpp' )

    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
