#ifndef __ASSOCIATION_MAPPER_BACKEND_H
#define __ASSOCIATION_MAPPER_BACKEND_H

#include <monitoring/association_mapper/AssociationMapper.hpp>

#define MONITORING_ASSOCIATION_MAPPER_INSTANCIATOR_NAME COMPONENT_INSTANCIATOR_NAME(monitoring_association_mapper)

#endif
