#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld.program(includes="",  use = "siox-core-ModuleLoader siox-knowledge-ReasonerStandardImplementation",  features='test cxx cxxprogram', target = 'reasoner-test', source = 'reasoner-test.cpp', install_path = None )

# -*- indent-tabs-mode: t -*-
