#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.shlib(includes="",  use = "siox-core-AutoConfigurator", target = 'siox-knowledge-OptimizerSkeleton', source = 'OptimizerSkeleton.cpp' )

    #bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
