#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld.program(includes="",  features='test cxx cxxprogram', use = "siox-knowledge-SystemInfoPersistency" ,  target = 'systeminfo_test', source = 'systeminfo_test.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
