#! /usr/bin/env python
# encoding: utf-8

def build(bld):
   #bld.shlib(includes="", use="BOOST siox-core-ContainerSerializer siox-core-AutoConfigurator ", target='siox-monitoring-ThreadedStatisticsCollector', source='ThreadedStatisticsCollector.cpp')
   bld.recurse(['plugins'], mandatory=True)


# -*- indent-tabs-mode: t -*-
