#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.shlib(include="include",  use = "AutoConfigurator", target = 'AnomalySkeleton', source = 'AnomalySkeleton.cpp' )

    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
