#! /usr/bin/env python
# encoding: utf-8

def build(bld):

    #bld.shlib(includes="include", use="BOOST core-container-serializer AutoConfigurator AutoRegistrar", target='StatisticsMultiplexerSync', source='StatisticsMultiplexerSync.cpp')

    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
