#! /usr/bin/env python
# encoding: utf-8

import os

def configure(conf):
   conf.check(features='c cprogram', lib=['hdf5','hdf5_hl'], cflags=['-I/usr/local/hdf5/include -L/usr/local/hdf5/lib'], uselib_store='HDF5')
   #conf.check(features='c cprogram', lib=['hdf5_hl'], cflags=['-I/usr/local/hdf5/include -L/usr/local/hdf5/lib'], uselib_store='HDF5HL')
   # cnf.check(features='cxx cxxprogram', lib=['m'], cflags=['-Wall'], defines=['var=foo'], uselib_store='M')
	# conf.check_cfg(package='libhdf5-7', uselib_store='HDF5',  args=['--cflags', '--libs'], mandatory=False)

def build(bld):
   try:
   		os.symlink(bld.path.abspath() + "/siox.conf", "build/monitoring/low-level-c/examples/hdf5/siox.conf")
   except OSError, e:
   	 	pass

   # -I/usr/local/hdf5/include -L/usr/local/hdf5/lib
   bld.program(includes="",  use = "siox-monitoring-siox-ll HDF5",  features='test c cprogram', target = 'hdf5-example', source = 'hdf5-example.c', install_path = None)

   pass

# -*- indent-tabs-mode: t -*-
