#! /usr/bin/env python
# encoding: utf-8

import os

def build(bld):
   #pass
   try:
   		os.symlink(bld.path.abspath() + "/siox.conf", "build/monitoring/low-level-c/test/siox.conf")
   except OSError, e:
   	 	pass
   bld.program(includes="",  use = "siox-monitoring-siox-ll",  features='test c cprogram', target = 'siox-monitoring-siox-ll-c-test', source = 'siox-monitoring-siox-ll-c-test.c', )


# -*- indent-tabs-mode: t -*-
