# - Find gio-unix-2.0


INCLUDE( FindPkgConfig )

IF ( GIOUNIX2_FIND_REQUIRED )
	SET( _pkgconfig_REQUIRED "REQUIRED" )
ELSE( GIOUNIX2_FIND_REQUIRED )
	SET( _pkgconfig_REQUIRED "" )	
ENDIF ( GIOUNIX2_FIND_REQUIRED )

IF ( GIOUNIX2_MIN_VERSION )
	PKG_SEARCH_MODULE( GIOUNIX2 ${_pkgconfig_REQUIRED} gio-unix-2.0 >=${GIOUNIX2_MIN_VERSION} )
ELSE ( GIOUNIX2_MIN_VERSION )
	PKG_SEARCH_MODULE( GIOUNIX2 ${_pkgconfig_REQUIRED} gio-unix-2.0  )
ENDIF ( GIOUNIX2_MIN_VERSION )


IF( NOT GIOUNIX2_FOUND AND NOT PKG_CONFIG_FOUND )
	FIND_PATH( GIOUNIX2_INCLUDE_DIRS gunixconnection.h PATH_SUFFIXES glib-2.0 )

	IF ( APPLE )
		FIND_LIBRARY( GIOUNIX2_LIBRARIES glib )
	ELSE ( APPLE )
		FIND_LIBRARY( GIOUNIX2_LIBRARIES NAMES gio-unix-2.0 glib-2.0 )
	ENDIF (APPLE)

	# Report results
	IF ( GIOUNIX2_LIBRARIES AND GIOUNIX2_INCLUDE_DIRS )	
		SET( GIOUNIX2_FOUND 1 )
		IF ( NOT GIOUNIX2_FIND_QUIETLY )
			MESSAGE( STATUS "Found gio-unix-2.0: ${GIOUNIX2_LIBRARIES} ${GIOUNIX2_INCLUDE_DIRS}" )
		ENDIF ( NOT GIOUNIX2_FIND_QUIETLY )
	ELSE ( GIOUNIX2_LIBRARIES AND GIOUNIX2_INCLUDE_DIRS )	
		IF ( GIOUNIX2_FIND_REQUIRED )
			MESSAGE( SEND_ERROR "Could not find gio-unix-2.0" )
		ELSE ( GIOUNIX2_FIND_REQUIRED )
			IF ( NOT GIOUNIX2_FIND_QUIETLY )
				MESSAGE( STATUS "Could not find gio-unix-2.0" )	
			ENDIF ( NOT GIOUNIX2_FIND_QUIETLY )
		ENDIF ( GIOUNIX2_FIND_REQUIRED )
	ENDIF ( GIOUNIX2_LIBRARIES AND GIOUNIX2_INCLUDE_DIRS )
ENDIF( NOT GIOUNIX2_FOUND AND NOT PKG_CONFIG_FOUND )

MARK_AS_ADVANCED( GIOUNIX2_LIBRARIES GIOUNIX2_INCLUDE_DIRS )
