#! /usr/bin/env python
# encoding: utf-8


def build(bld):
    #bld.shlib( use = "GMODULES" ,  target = 'activity_multiplexer', source = 'activity_multiplexer.cpp' )
    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
