#! /usr/bin/env python
# encoding: utf-8


def build(bld):
    bld.shlib( use = "GMODULES" ,  target = 'ActivityMultiplexer_Impl1',  lib=['pthread'], source = 'ActivityMultiplexer_Impl1.cpp' )

    bld.recurse(['test', 'plugins'], mandatory=True)
    #bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
