#! /usr/bin/env python
# encoding: utf-8

from waflib import Logs

import os

def build(bld):
	bld.shlib(includes="#",  target = "siox-util", source = 'autoLoadModules.cpp' )


# -*- indent-tabs-mode: t -*-
