#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.shlib(includes="",  use = "AutoConfigurator BOOST", target = 'OSMemUsage', source = 'OSMemUsage.cpp' )

    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
