#! /usr/bin/env python
# encoding: utf-8

def options(conf):
	conf.recurse(['modules'], mandatory=True)

def configure(conf):
	conf.recurse(['modules'], mandatory=True)

def build(bld):
	bld.recurse(['modules'], mandatory=True)


# -*- indent-tabs-mode: t -*-
