#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.shlib(includes="include",  use = "AutoConfigurator", target = 'iostatsSkel', source = 'iostats.cpp' )

    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
