#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.shlib(includes="",  use = "siox-core-AutoConfigurator", target = 'siox-monitoring-statisticsPlugin-providerskel-min', source = 'iostats.cpp', install_path = None )

    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
