#! /usr/bin/env python
# encoding: utf-8


def build(bld):
	bld.shlib(includes="",  use ="BOOST ", target = 'siox-core-ContainerSerializer', source = 'container-serializer.cpp' )
	bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
