#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld.program(includes="",  features='test cxx cxxprogram', use = "siox-core-comm-multiMessageService siox-core-comm-inmemory siox-core-ModuleLoader", target = 'test-comm-mmts',	source = 'test-comm-interfaces.cpp', install_path = None, )

# -*- indent-tabs-mode: t -*-
