#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    #bld.program(includes="",  features='test cxx cxxprogram', use = "siox-monitoring-activityPlugin-ActivityForwarder", target = 'ActivityForwarderTest', source = 'ActivityForwarderTest.cpp', install_path = 'None')
    pass
