#! /usr/bin/env python
# encoding: utf-8

def build(bld):
   bld.program(include="include",  use = "siox-ll",  features='test c cprogram', target = 'siox-ll-c-test', source = 'siox-ll-c-test.c', install_path = None,)


# -*- indent-tabs-mode: t -*-
