#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(includes="",  features='test cxx cxxprogram', use = "siox-monitoring-ThreadedStatisticsCollector siox-core-AutoConfigurator", target = 'ThreadedStatisticsCollectorTest', source = 'ThreadedStatisticsCollectorTest.cpp', install_path = None)

# -*- indent-tabs-mode: t -*-
