#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    # TODO: build tests
    #bld.program(includes="",  features='test cxx cxxprogram', use = "siox-monitoring-StatisticsMultiplexerSync siox-core-ModuleLoader", target = 'StatisticsMultiplexerTest', source = "StatisticsMultiplexerTest.cpp", install_path = None)

    pass



# -*- indent-tabs-mode: t -*-
