#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    # TODO: build tests
    #bld.program(include="include",  features='test cxx cxxprogram', use = "StatisticsMultiplexerSync module-loader", target = 'StatisticsMultiplexerTest', source = "StatisticsMultiplexerTest.cpp", install_path = None)

    pass



# -*- indent-tabs-mode: t -*-
