#! /usr/bin/env python
# encoding: utf-8


def build(bld):
    bld.shlib( target = "siox-ll",  lib=['pthread'], source = 'siox-ll.cpp' )
    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
