#! /usr/bin/env python
# encoding: utf-8


def build(bld):
    bld.shlib(includes="",  target = "siox-ll", use = "module-loader AutoConfigurator", lib=['pthread', 'rt'], source = 'siox-ll.cpp' )
    bld.recurse(['test'], mandatory=True)
    bld.recurse(['examples'], mandatory=True)


# -*- indent-tabs-mode: t -*-
