#ifndef SIOX_MMULTIPLEXER_MODULE_PLUGIN_
#define SIOX_MMULTIPLEXER_MODULE_PLUGIN_

#include <monitoring/statistics/multiplexer/StatisticsMultiplexerPlugin.hpp>

#define MONITORING_STATISTICS_MULTIPLEXER_PLUGIN_INSTANCIATOR_NAME MODULE_INSTANCIATOR_NAME(monitoring_statisticsmultiplexer_plugin)

#endif
