#ifndef SIOX_DATATYPE_HELPER_MPI_
#define SIOX_DATATYPE_HELPER_MPI_

// Generic flags for file open modes
enum MPIFileFlags {
	SIOX_MPI_MODE_RDONLY = 1,
	SIOX_MPI_MODE_RDWR = 2,
	SIOX_MPI_MODE_WRONLY = 4,
	SIOX_MPI_MODE_CREATE = 8,
	SIOX_MPI_MODE_EXCL = 16,
	SIOX_MPI_MODE_DELETE_ON_CLOSE = 32,
	SIOX_MPI_MODE_UNIQUE_OPEN = 64,
	SIOX_MPI_MODE_SEQUENTIAL = 128,
	SIOX_MPI_MODE_APPEND = 256
};


enum MPIThreadLevel{
	SIOX_MPI_THREAD_SINGLE = 1,
	SIOX_MPI_THREAD_FUNNELED = 2,
	SIOX_MPI_THREAD_SERIALIZED = 4,
	SIOX_MPI_THREAD_MULTIPLE = 8
};

enum MPIDatatype{
	SIOX_MPI_TYPE_UNKNOWN = 1073741824,
	SIOX_MPI_TYPE_CHAR,
	SIOX_MPI_TYPE_SHORT,
	SIOX_MPI_TYPE_INT,
	SIOX_MPI_TYPE_LONG,
	SIOX_MPI_TYPE_UNSIGNED_CHAR,
	SIOX_MPI_TYPE_UNSIGNED_SHORT,
	SIOX_MPI_TYPE_UNSIGNED_LONG,
	SIOX_MPI_TYPE_UNSIGNED,
	SIOX_MPI_TYPE_FLOAT,
	SIOX_MPI_TYPE_DOUBLE,
	SIOX_MPI_TYPE_LONG_DOUBLE,
	SIOX_MPI_TYPE_BYTE,
	SIOX_MPI_TYPE_PACKED
};

#define SIOX_MPI_COMM_WORLD (~(0ll))
#define SIOX_MPI_COMM_SELF (~(0ll)-1)


#endif
