#! /usr/bin/env python
# encoding: utf-8

def build(bld):	
	bld(rule="${CODEGEN} -o ${TGT} -i ${SRC}", source="CommASIOOptions.hpp", target="BoostXMLSerializable.cpp", name="CommASIOOptions")

	bld.shlib(includes="/opt/protobuf/include #", use="BOOST ", target = "siox-core-comm-asio", source = 'ASIOConnection.cpp  ASIOConnectionFactory.cpp  ASIOConnectionMessage.cpp  ASIOServerFactory.cpp  ASIOServiceClient.cpp  ASIOServiceServer.cpp  CommASIO.cpp tcp/TCPServer.cpp tcp/TCPConnection.cpp ipc/IPCServer.cpp ipc/IPCConnection.cpp  BoostXMLSerializable.cpp', depends_on="CommASIOOptions")
	
	bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
