#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(include="include",  features='test cxx cxxprogram', use = "module-loader FileBasedSystemInformation", target = 'filebasedsysteminformation-test', source = 'filebasedsysteminformation-test.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
