#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    conf.recurse(['hdf5'], mandatory=True)

def build(bld):
    bld.recurse(['hdf5'], mandatory=True)
    bld.recurse(['mock-up-fs'], mandatory=True)
    #pass

# -*- indent-tabs-mode: t -*-
