#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld.program(include="include",  use = "optimizer module-loader FileOntology FileOntologyOptions",  features='test cxx cxxprogram', target = 'optimizer-test', source = 'optimizer-test.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
