#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld.program(includes="",  use = "optimizer siox-core-ModuleLoader siox-monitoring-FileOntology FileOntologyOptions",  features='test cxx cxxprogram', target = 'optimizer-test', source = 'optimizer-test.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
