#! /usr/bin/env python
# encoding: utf-8

def build(bld):	
	bld(rule="${CODEGEN} -o ${TGT} -i ${SRC}", source="GIOOptions.hpp", target="BoostXMLSerializable.cpp", name="GIOOptions")

	bld.shlib(includes="", use="BOOST ", target = "siox-core-comm-gio", source = 'GIO.cpp BoostXMLSerializable.cpp', depends_on="GIOOptions")
	
	bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
