#! /usr/bin/env python
# encoding: utf-8

def build(bld):
     pass
#    bld.shlib(includes="",  use = "siox-core-AutoConfigurator", target = 'siox-monitoring-activityPlugin-ActivityForwarder', source ='ActivityForwarder.cpp' )

#    bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
