#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld(rule="${CODEGEN} -o ${TGT} -i ${SRC}", source="ActivityForwarderOptions.hpp", target="BoostXMLSerializable.cpp", name="ActivityForwarderOptions.hpp")

	bld.shlib(includes="",  use = "siox-core-AutoConfigurator", target = 'siox-monitoring-activityPlugin-ActivityForwarder', source ='ActivityForwarder.cpp BoostXMLSerializable.cpp', depends_on = "ActivityForwarderOptions.hpp" )

	bld.recurse(['test'], mandatory=True)


# -*- indent-tabs-mode: t -*-
