#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(includes="include",  features='test cxx cxxprogram', use = "OSMemUsage AutoConfigurator", target = 'OSMemUsageTest', source = 'OSMemUsageTest.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
