#! /usr/bin/env python
# encoding: utf-8

import os

def build(bld):
   #pass
   try:
   		os.symlink(bld.path.abspath() + "/siox.conf", "build/monitoring/low-level-c/examples/mock-up-fs/siox.conf")
   except OSError, e:
   	 	pass
   
   bld.shlib(includes="include",  target = "mufs", use = "siox-ll", source = 'mufs.c' )
   #bld.shlib(includes="include",  target = "mufs", use = "module-loader AutoConfigurator", lib=['pthread', 'rt'], source = 'siox-ll.cpp' )

   bld.program(includes="include",  use = "siox-ll mufs ActivityBuilder",  features='test c cprogram', target = 'mockupfs-example', source = 'mockupfs-example.c', install_path = None,)


# -*- indent-tabs-mode: t -*-
