#!/bin/bash

# @author: JK

function ABORT(){
	echo "Syntax:"
	echo "	$0 <LAYER1_TO_INSTRUMENT,LAYER2,...> <TYPE:dlsym|wrap> <ORIGINAL_PROGRAMM>"
	echo "	e.g. $0 posix,hdf5 wrap gcc test.c -o test.o"
	echo "	e.g. $0 posix,hdf5 dlsym ls /home"
	echo
	echo "Instrumention for the following layers is available:"
	echo "$AVAILABLE_WRAPPERS"
	exit 1
}

INSTALL_DIR=$(dirname $(dirname $0))


# Verbosity level
VERBOSE=
if [[ "$1" == "-h" ]];then
	ABORT
fi

if [[ "$1" == "-v" ]];	then
	VERBOSE=1
	shift
fi

# Layers to instrument are specified by the user
LAYERS="$1"
shift

# Type of the instrumentation
TYPE="dlsym"

if [[ "$1" == "dlsym" ]];then
	TYPE="dlsym"
	shift
fi
if [[ "$1" == "wrap" ]];then
	TYPE="wrap"
	shift
fi

pushd $INSTALL_DIR/lib >/dev/null
AVAILABLE_WRAPPERS=$(ls libsiox-*dlsym* | sed "s/libsiox-//g" | sed "s/-dlsym.*//" )
popd >/dev/null

if [[ "$1" == "" ]] ; then
	ABORT
fi

if [ $VERBOSE ];then
	echo "INFO: $AVAILABLE_WRAPPERS"
fi

# checking availability of selected wrappers:
LAYERS_TO_INSTRUMENT=(${LAYERS//,/ })

LDSTRING=""
WRAPSTRING=""
WRAPLIBS="-L $INSTALL_DIR/lib/ -Wl,-rpath $INSTALL_DIR/lib/"
for l in "${LAYERS_TO_INSTRUMENT[@]}";do
	if [[ $AVAILABLE_WRAPPERS != *$l* ]]; then
		echo "Invalid layer: $l"
		ABORT
	fi
	LDSTRING="$INSTALL_DIR/lib/libsiox-$l-dlsym.so $LDSTRING"
	WRAPSTRING="$(cat $INSTALL_DIR/lib/$l.wrap) $WRAPSTRING"
	WRAPLIBS="$WRAPLIBS -l siox-$l-wrap"
done

if [[ $TYPE == "dlsym" ]] ; then
	
	if [ $VERBOSE ];then
		echo "LD_PRELOAD=\"$LDSTRING\" $@"
	fi

	echo "[EXE] $LAYERS \"$@\" "
	export LD_LIBRARY_PATH=$INSTALL_DIR/lib:$LD_LIBRARY_PATH

	LD_PRELOAD="INFO: $LDSTRING" $@
else

	if [ $VERBOSE ];then
		echo "INFO: $@ $WRAPSTRING $WRAPLIBS"
	fi

	echo "[CC] $LAYERS \"$@\""
	$@ $WRAPSTRING $WRAPLIBS
fi
