#ifndef SIOX_ACTIVITY_MULTIPLEXER_MODULE
#define SIOX_ACTIVITY_MULTIPLEXER_MODULE

#include <monitoring/activity_multiplexer/ActivityMultiplexer.hpp>

#define MONITORING_ACTIVITY_MULTIPLEXER_INSTANCIATOR_NAME MODULE_INSTANCIATOR_NAME(monitoring_activitymultiplexer)

#endif
