#ifndef SIOX_ACTIVITY_MULTIPLEXER_MODULE_PLUGIN_
#define SIOX_ACTIVITY_MULTIPLEXER_MODULE_PLUGIN_
#include <monitoring/activity_multiplexer/ActivityMultiplexerPlugin.hpp>

#define MONITORING_ACTIVITY_MULTIPLEXER_PLUGIN_INSTANCIATOR_NAME MODULE_INSTANCIATOR_NAME(monitoring_activitymultiplexer_plugin)

#endif
