#! /usr/bin/env python
# encoding: utf-8

import os

def build(bld):
   bld.program(includes="#", use="siox-core-ModuleLoader siox-tools-TraceReader", features='cxx cprogram test', target = 'TraceReaderTest', source = 'TraceReaderTest.cpp', install_path = None )

   try:
   		for name in  ["activities", "association", "ontology", "system-info"] : 
   			name = name + ".dat"
   			os.symlink(bld.path.abspath() + "/" + name, "build/" + bld.path.relpath() + "/" + name)

   except OSError, e:
   	 	pass


# -*- indent-tabs-mode: t -*-
