#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(features='test cxx cxxprogram', use='ActivityBuilder', target='ActivityBuilderTest', source='activity_builder-test.cpp', linkflags='-lrt', install_path = None)


# -*- indent-tabs-mode: t -*-
