#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(includes="",  features='test cxx cxxprogram', use = "iostats AutoConfigurator", target = 'iostatsTestSkel', source = 'iostatsTest.cpp', install_path = None,)

# -*- indent-tabs-mode: t -*-
