#! /usr/bin/env python
# encoding: utf-8

def build(bld):  
	pass  
    #bld.program(includes="",  features='test cxx cxxprogram', use = "OptimizerDefaultImpl module-loader", target = 'OptimizerTest', source = "OptimizerTest.cpp", install_path = None)



# -*- indent-tabs-mode: t -*-
