#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    pass
    #bld.program(includes="include",  features='test cxx cxxprogram', use = "AnomalySkeleton", target = 'AnomalySkeletonTest', source = 'AnomalySkeletonTest.cpp', install_path = 'None')
